### PR TITLE
ExploreDetail page: Navigation, main structure and configure button + dropdown [wip]

### PR DESCRIPTION
**Pull request by pablopareja**
@mbarrenechea could you please have a look at this?
I've tried to get the the configure dropdown working but I got stuck trying to get rid of the button arrow when using the Dropdown component.
Thanks!

### CODE REVIEW

**Comment by pablopareja** [comment]
@mbarrenechea I've just pushed a commit including the new Dropdown component already working with the configure button

**Review by mbarrenechea — CHANGES_REQUESTED** [review]
I have this warning in the console => "Warning: Failed prop type: The prop `onChangeVisibility` is marked as required in `Dropdown`, but its value is `undefined`. in Dropdown"

**Review by mbarrenechea — COMMENTED** [review]
Try to review the es-lint, I see too many spaces and thing that shouldn't be there

**Comment by pablopareja** [comment]
I have fixed most of the problems identified by eslint with the last commit. Regarding the warning, it's originated from the _other_ Dropdown instance, i.e. the one from the navigation header.
Should we create an ad-hoc Dropdown for that or try to reuse the Dropdown used here instead?

**Review by mbarrenechea — APPROVED** [review]

**Pull request merged**
